CREATE TABLE tblRollup_Snapshot (
    ETL_DATE DATE NOT NULL,
    ACT_ID VARCHAR(50) NOT NULL,
    IMPLANT_UNIT_FORECAST INT,
    ACTUAL_IMPLANTS INT,
    IMPLANT_DELTA INT,
    IMPL_REASON_FOR_VARIANCE VARCHAR(MAX),
    REV_UNIT_FORECAST INT,
    ACTUAL_REV_UNITS INT,
    REV_UNIT_DELTA INT,
    REV_REASON_FOR_VARIANCE VARCHAR(MAX),
    CONSTRAINT PK_tblRollup_Snapshot PRIMARY KEY (ETL_DATE, ACT_ID)
);